### ISSUE TITLE
Cannot import content scripts

### ISSUE THREAD

**Issue by avi12** [extend-chrome/rollup-plugin-chrome-extension#60]
### Google search terms
Didn't try to Google the issue, but rather to look into boilerplate examples

### Describe the bug
If I try to import the files like so:
```json
{
  "content_scripts": [
    {
      "matches": ["https://example.com/*"],
      "js": [
         "lib/some-library.js",
         "scripts/content-script.js"
       ]
    }
  ]
}
```
Then the output of `lib/some-library.js` will be empty.
Otherwise, if I do:
```json
{
  "content_scripts": [
    {
      "matches": ["https://example.com/*"],
      "js": ["scripts/content-script.js"]
    }
  ]
}
```
`scripts/content-script.js`
```js
import { someFunction } from "../lib/some-library";
```
The output will be:
```json
{
  "web_accessible_resources": [
    "some-library-cd51b70d.js",
    "scripts/content-script.js"
  ]
}
```
What will be imported in `scripts/content-script.js`:
```js
import { someFunction } from "../some-library-cd51b70d-c791af63.js";
```
Because the filename to be imported is different from the one that actually exists, it will fail.

### How do we reproduce?
Simply create 2 content scripts that need to be linked and import one's function/variable/whatever into the other.

### Expected behavior
It should work correctly.

### Actual behavior
It imports a different filename than there actually is.

### Please complete the following information:

- Library Version: ^3.5.1
- Operating System: Windows 10 20H2 build 19042.685
- Browser: Chromium Edge 88.0.705.29
- Node Version: 14.15.3

### Additional context
`rollup.config.js`
```js
import {
  chromeExtension,
  simpleReloader
} from "rollup-plugin-chrome-extension";
import { terser } from "rollup-plugin-terser";
import { emptyDir } from "rollup-plugin-empty-dir";
import zip from "rollup-plugin-zip";
import resolve from "@rollup/plugin-node-resolve";

const isProduction = !process.env.ROLLUP_WATCH;

export default {
  input: "src/manifest.json",
  output: {
    dir: "dist",
    format: "esm"
  },
  plugins: [
    // always put chromeExtension() before other plugins
    chromeExtension(),
    !isProduction && simpleReloader(),
    resolve(),
    emptyDir(),
    isProduction && terser(),
    isProduction && zip({ dir: "dist_packed" })
  ]
};

```

**Comment by AmySteam** [comment]
Hey there! 🙂Thank you for putting this together! We'll be pushing a patch later today 👍

**Comment by jacksteamdev** [comment]
@avi12 rollup-plugin-chrome-extension@3.5.2 was published just now, which should fix the problem. Thanks for putting together this issue!

**Comment by avi12** [comment]
It did fix a lot of stuff, so now it loads correctly in Edge
But, for a strange reason, not on Firefox (loaded via [web-ext](https://www.npmjs.com/package/web-ext))

**Comment by jacksteamdev** [comment]
@avi12 Firefox is not supported yet. We're working on it! 😅 They have implemented the content script environment differently than Chromium based browsers. This is being tracked in issue #56.

Since things are working as expected for this issue, I'm going to close it. Thanks for helping us make `rollup-plugin-chrome-extension` better!

**Comment by avi12** [comment]
I'd appreciate it if you could apply a temporary fix in which you simply split the `import` statements into different files and list each in the manifest
Then, output to a directory such as `{dirName}-firefox`

**Comment by rafalkrupinski** [comment]
I still have this problem with 3.5.2, but instead of having the hex number appended twice, it's not appended at all, with the same result

**Comment by jacksteamdev** [comment]
@rafalkrupinski If you're still having a problem with the missing hash, could you open an issue and include a link to a minimal reproduction repo?

Closing this since the original issue is fixed.
